
site_name: My Notes
nav:
    - Home: index.md
    - Bacula: bacula.md
    - Base64: base64.md
    - Bash Stuff: bashstuff.md
    - Blue Parrot: blueparrot.md
    - Exiftool: exiftool.md
    - Fedora Keyring: fedora_keyring.md
    - FFMEG: ffmpeg.md
    - GiT: git.md
    - ImageMagick: imagemagick.md
    - JS Notes: js_notes.md
    - Keybase: keybase.md
    - Linux User Admin: linuxuser.md
    - Linux Tape Drives: linuxtapedrives.md
    - LVM - Linux Volume Manager: lvm.md
    - MAC - Apple: mac_apple.md
    - Markdown: markdown.md
    - Mount LUKS Encrypted Media: luksmount.md
    - MariaDB/MySQL: mysql.md
    - OpenVPN: openvpn.md
    - PGP: pgp.md
    - RDesktop: rdesktop.md
    - SE Linux: se_linux.md
    - SSH: ssh.md
    - MS Teams: ms_teams.md
    - VI Editor: vi_editor.md
    - Windows: windows.md
    - X11 Forwarding: x11_forwarding.md
    - Youtube-dl: youtube_dl.md
theme: readthedocs
