rm -f alter_table.md
rm -f alter_user.md
rm -f bmdi_cuf.md
rm -f commandline.md
rm -f concatenate_prepend_data.md
rm -f conditional_update.md
rm -f create_stored_procedure.md
rm -f create_users.md
rm -f datatypes.md
rm -f date.md
rm -f datetime_vs_timestamp.md
rm -f display_foreign_key_references.md
rm -f dumpdb.md
rm -f duplicate_data.md
rm -f enable_remote_connection_for_specific_IP_address.md
rm -f enum.md
rm -f event.md
rm -f file_rename.md
rm -f foreign_key_constraint.md
rm -f grant_privileges.md
rm -f groupby.md
rm -f if_case_statements.md
rm -f increment_numbered_results.md
rm -f insert_into_table_from_current.md
rm -f int_bigint.md
rm -f join_with_no_where.md
rm -f last_insert_id.md
rm -f load_input_csv_data.md
rm -f locate_mysql_database_files.md
rm -f mysql_timezone_timestamp_calculations.md
rm -f order_by-sort_by.md
rm -f output_data_to_a_file.md
rm -f padding_zeros.md
rm -f password.md
rm -f rename.md
rm -f select_across_databases.md
rm -f select_blobdata.md
rm -f select_for_null.mysql.md
rm -f select_year_month_avg.md
rm -f show_columns.md
rm -f show.md
rm -f show_table.md
rm -f show_table_size.md
rm -f show_views.md
rm -f stateflags.md
rm -f states_electoral_votes.md
rm -f states.md
rm -f stored_procedure.md
rm -f triggers2.md
rm -f triggers.md
rm -f triggertest.md
rm -f trim_whitespace.md
rm -f united_states.md
rm -f unsigned.md
rm -f update_electoral_votes.md
rm -f update.md
rm -f us_presidents.md
rm -f wordpress.md
